name: tortoise_techno
description: "A Flutter-based company website for Tortoise Techno Solutions Pvt."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase core and Firestore
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

  # UI / Styling
  google_fonts: ^6.1.0
  responsive_framework: ^1.1.0
  url_launcher: ^6.3.2
  provider: ^6.1.2

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.0
  http: ^1.4.0
  carousel_slider: ^5.1.1
  supabase_flutter: ^2.9.1
  firebase_storage: ^12.4.10
  firebase_core_web: ^2.24.1
  cloud_firestore_web: ^4.4.12
  firebase_storage_web: ^3.10.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banners/
    - assets/images/icons/
    - assets/fonts/
